require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: '2.4.1'
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'


Metrics/LineLength:
  Enabled: true
  Max: 160

Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 200

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Enabled: true
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 7

Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'config/application.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'

Style/NumericLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded
